name: Node CI (extension)

on: [push]

jobs:
  build:
    runs-on: macOS-10.14

    strategy:
      matrix:
        node-version: [10.16]

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: npm install and test
        run: |
          yarn
          yarn run compile
          yarn run compile-test
          yarn test
        env:
          CI: true
