name: Node CI (extension)

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.16]

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Start xvfb
        run: /usr/bin/Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &

      - name: npm install and test
        run: |
          npm ci
          npm run compile
          npm run compile-test
          npm test
        env:
          CI: true
          CODE_VERSION: ''
          DISPLAY: ':99.0'
