name: Node CI

on: [push]

jobs:
  build:
    runs-on: macos-latest

    strategy:
      matrix:
        node-version: [10.16]

    steps:
      - uses: actions/checkout@master
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@master
        with:
          node-version: ${{ matrix.node-version }}
      - name: npm install, build, and test
        run: |
          yarn install
          yarn run compile && yarn run compile-test
          yarn test
        env:
          CI: true
